[2024-03-21T03:04:00.601+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-03-21T03:03:56.204458+00:00 [queued]>
[2024-03-21T03:04:00.627+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-03-21T03:03:56.204458+00:00 [queued]>
[2024-03-21T03:04:00.628+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-21T03:04:00.682+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): inaccurate> on 2024-03-21 03:03:56.204458+00:00
[2024-03-21T03:04:00.705+0000] {standard_task_runner.py:60} INFO - Started process 105 to run task
[2024-03-21T03:04:00.719+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2024-03-21T03:03:56.204458+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmps1vz1vjo']
[2024-03-21T03:04:00.728+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask inaccurate
[2024-03-21T03:04:00.911+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.inaccurate manual__2024-03-21T03:03:56.204458+00:00 [running]> on host 0bc8edee533b
[2024-03-21T03:04:01.092+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T03:03:56.204458+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-21T03:03:56.204458+00:00'
[2024-03-21T03:04:01.097+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-21T03:04:01.100+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-03-21T03:04:01.133+0000] {subprocess.py:86} INFO - Output:
[2024-03-21T03:04:01.137+0000] {subprocess.py:93} INFO - inaccurate
[2024-03-21T03:04:01.138+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-21T03:04:01.192+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20240321T030356, start_date=20240321T030400, end_date=20240321T030401
[2024-03-21T03:04:01.271+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-21T03:04:01.325+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
